project:
  type: default
  output-dir: _output

lang: es

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-title: "Índice de contenidos"
    number-sections: true
    smooth-scroll: true
    highlight-style: github
    code-copy: false
  pdf:
    documentclass: article
    papersize: a4
    fontsize: 12pt
    geometry:
      - margin=2.5cm
    linestretch: 1.5
    cite-method: biblatex
    keep-tex: true
    number-sections: true
    colorlinks: true

bibliography: references.bib
csl: apa.csl
